version: "3.7"
services:
  app:
    image: mindfoundation/asc-studymonitor
    build:
      context: .
      args:
        - SOURCE_COMMIT=${SOURCE_COMMIT}
    expose:
      - 8000
    secrets:
      - asc-secret
    stop_signal: SIGINT
    restart: always

  mongo:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: integration
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb-data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./etc/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - 80:80

volumes:
  mongodb-data:
    name: asc-mongodb-dev

secrets:
  asc-secret:
    file: asc-secret.json