version: "3.7"
services:
  app:
    image: mindfoundation/asc-studymonitor
    build: .
    expose:
      - 8000
    secrets:
      - mendeley-secret
    stop_signal: SIGINT
    restart: always

  redis:
    image: redis:alpine

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - 80:80

secrets:
  mendeley-secret:
    file: mendeley-secret.json
