version: "3.7"
services:
  app:
    image: mindfoundation/asc-studymonitor
    build: .
    expose:
      - 8000
    secrets:
      - asc-secret
    stop_signal: SIGINT
    restart: always

  mongo:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: integration
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - mongodb-data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
      
    ports:
      - 80:80

  cache_warmer:
    build: cache-warmer/

secrets:
  asc-secret:
    file: asc-secret.json