[tool.poetry]
name = "ASCMonitor"
version = "1.0.0"
description = ""
authors = ["Felix Peppert <felix.peppert@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
mendeley = "^0.3.2"
requests = "^2.5"
flask = "^1.1"
redis = "^3.3"
msgpack-python = "^0.5.6"
gunicorn = "^19.9"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
