name: Backend Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with pylint
        working-directory: backend
        run: poetry run pylint ascmonitor
      - name: Typecheck with mypy
        working-directory: backend
        run: poetry run mypy ascmonitor
      - name: Test with pytest
        working-directory: backend
        run: poetry run pytest
