name: Unit Tests

on: push

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint with pylint
        working-directory: backend
        run: poetry run pylint ascmonitor

      - name: Typecheck with mypy
        working-directory: backend
        run: poetry run mypy ascmonitor

      - name: Test with pytest
        working-directory: backend
        run: poetry run pytest

  test-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client install --frozen-lockfile

      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client build

      - name: yarn lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client lint

      - name: yarn test:unit
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client test --ci --collect-coverage
